export let Players = [{
        img1: '/players-img/lbj-img1.png',
        img2: '/players-img/lbj-img2.png',
        name: "Lebron James",
        position: 'Forward',
        ppg: 29.5,
        rpg: 8.4,
        apg: 6.9,
        p3p: 30.8,
        fg: 50.1,
    },
    {
        img1: '/players-img/lbj-img1.png',
        img2: '/',
        name: "Stephen Curry",
        position: 'Point Guard',
        ppg: 29.8,
        rpg: 6.2,
        apg: 6.2,
        p3p: 43.5,
        fg: 49.9,
    },
    {
        img1: '/players-img/lbj-img1.png',
        img2: '/',
        name: "Kyrie Irving",
        position: 'Point Guard',
        ppg: 27.4,
        rpg: 5.1,
        apg: 5.6,
        p3p: 38.5,
        fg: 49.4,
    },
    {
        img1: '/players-img/lbj-img1.png',
        img2: '/',
        name: "Luca Dončić",
        position: 'Shooting Guard',
        ppg: 33.0,
        rpg: 8.6,
        apg: 8.0,
        p3p: 34.9,
        fg: 50.0,
    },
    {
        img1: '/players-img/lbj-img1.png',
        img2: '/',
        name: "Joel Embiid",
        position: 'Center',
        ppg: 33.5,
        rpg: 10.2,
        apg: 4.2,
        p3p: 33.3,
        fg: 66.7,
    },
    {
        img1: '/players-img/lbj-img1.png',
        img2: '/',
        name: "Giannis Antetokounmpo",
        position: 'Power Forward',
        ppg: 31.4,
        rpg: 11.9,
        apg: 5.5,
        p3p: 28.4,
        fg: 54.2,
    },
    {
        img1: '/players-img/lbj-img1.png',
        img2: '/',
        name: "Stephen Curry",
        position: 'Point Guard',
        ppg: 29.8,
        rpg: 6.2,
        apg: 6.2,
        p3p: 43.5,
        fg: 49.9,
    },
    {
        img1: '/players-img/lbj-img1.png',
        img2: '/',
        name: "Kyrie Irving",
        position: 'Point Guard',
        ppg: 27.4,
        rpg: 5.1,
        apg: 5.6,
        p3p: 38.5,
        fg: 49.4,
    },
    {
        img1: '/players-img/lbj-img1.png',
        img2: '/',
        name: "Luca Dončić",
        position: 'Shooting Guard',
        ppg: 33.0,
        rpg: 8.6,
        apg: 8.0,
        p3p: 34.9,
        fg: 50.0,
    },
    {
        img1: '/players-img/lbj-img1.png',
        img2: '/',
        name: "Joel Embiid",
        position: 'Center',
        ppg: 33.5,
        rpg: 10.2,
        apg: 4.2,
        p3p: 33.3,
        fg: 66.7,
    },
    {
        img1: '/players-img/lbj-img1.png',
        img2: '/',
        name: "Giannis Antetokounmpo",
        position: 'Power Forward',
        ppg: 31.4,
        rpg: 11.9,
        apg: 5.5,
        p3p: 28.4,
        fg: 54.2,
    }
]